import React, { useState } from 'react';
import { Copy, Check, Hash, Building2, Ruler, Compass, Layers, UserCheck, ShieldCheck, Download, Box, AreaChart } from 'lucide-react';
import { Unit } from '../../types';
import './UnitCard.css';

interface UnitCardProps {
  unit: Unit | null;
}

export default function UnitCard({ unit }: UnitCardProps) {
  const [copied, setCopied] = useState(false);

  if (!unit) {
    return (
      <div className="unit-card empty glass-panel" id="unit-detail-panel">
        <div className="empty-state-content">
          <div className="empty-icon-wrapper">
            <Building2 size={36} className="text-secondary" />
          </div>
          <h4 className="empty-title">Select Volumetric Unit</h4>
          <p className="empty-subtitle">
            Click on any 3D extruded unit in the map viewer to reveal its ULPIN hash, elevation range, owner, and coordinates.
          </p>
          <div className="ulpin-format-hint">
            <Hash size={12} />
            <code className="text-[0.68rem] text-cyan-400/70">PARCEL_ID-BLDG-F01-UA01-geohash</code>
          </div>
        </div>
      </div>
    );
  }

  const handleCopyULPIN = async () => {
    try {
      await navigator.clipboard.writeText(unit.ulpin);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const downloadCertificate = () => {
    // Parse ULPIN parts matching AI Blueprint format
    const ulpinParts = unit.ulpin.split('-');
    const geohash = ulpinParts[ulpinParts.length - 1] || '';
      const floorHeight = unit.floor_height_m ?? ((unit.z_max ?? 0) - (unit.z_min ?? 0));
      const certFloorNum = unit.floor_number ?? unit.floor ?? 1;
      const certAreaSqm  = unit.area_sqm ?? (unit.area_sqft ? unit.area_sqft / 10.764 : null);
      const certZmin     = unit.z_min ?? (certFloorNum - 1) * (unit.floor_height_m ?? 3.5);
      const certZmax     = unit.z_max ?? certFloorNum * (unit.floor_height_m ?? 3.5);

    const certText = `
===========================================
   3D ULPIN CADASTRAL DIGITAL CERTIFICATE
===========================================
Generated by: 3D-ULPIN MVP System (ISO 19152 LADM Compliant)
Generated at: ${new Date().toISOString()}

--- UNIT IDENTIFICATION ---
3D ULPIN Code : ${unit.ulpin}
Unit ID       : ${unit.unit_id}
Unit Name     : ${unit.unit_name || 'Standard Cadastral Unit'}
Geohash (7ch) : ${geohash}

--- SPATIAL COORDINATES ---
Floor Level   : ${certFloorNum} (${certFloorNum === 1 ? 'Ground' : `${certFloorNum - 1}F`})
Z Min (m)     : +${Number(certZmin).toFixed(2)} m above ground
Z Max (m)     : +${Number(certZmax).toFixed(2)} m above ground
Floor Height  : ${Number(floorHeight).toFixed(2)} m
Floor Area    : ${certAreaSqm != null ? Number(certAreaSqm).toFixed(2) : '—'} m²
Centroid      : Lat ${unit.centroid?.[0] != null ? Number(unit.centroid[0]).toFixed(6) : '—'}, Lng ${unit.centroid?.[1] != null ? Number(unit.centroid[1]).toFixed(6) : '—'}

--- OWNERSHIP & USAGE ---
Registered Owner : ${unit.owner || 'Government Cadastral Registry'}
Status           : ${unit.status || 'Registered'}
Use Type         : ${unit.use_type || 'Residential'}

--- VALIDATION ---
Spatial Status   : VALID — Non-Overlapping (ISO 19152 LADM 3D)
Overlap Check    : PASS ✓
Boundary Check   : PASS ✓
Engine           : deck.gl + MapLibre GL JS 3D Volumetric Extrusion

===========================================
    `.trim();

    const blob = new Blob([certText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `3D-ULPIN-${unit.unit_id}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  // ── Safe field normalization (handles both mock & backend unit shapes) ──
  const floorNum    = unit.floor_number ?? unit.floor ?? 1;
  const floorHtM    = unit.floor_height_m ?? 3.5;
  const zMin        = unit.z_min ?? (floorNum - 1) * floorHtM;
  const zMax        = unit.z_max ?? floorNum * floorHtM;
  const floorHeight = unit.floor_height_m ?? parseFloat(((zMax - zMin)).toFixed(2));
  const areaSqm     = unit.area_sqm ?? (unit.area_sqft ? unit.area_sqft / 10.764 : null);
  const floorLabel  = floorNum === 1 ? 'Ground Floor' : `Floor ${floorNum - 1}F`;
  const centroid    = unit.centroid ?? null;

  return (
    <div className="unit-card active glass-panel fade-in" id="unit-detail-panel">
      {/* Header */}
      <div className="unit-card-header">
        <div className="header-info">
          <span className="unit-tag">Floor {floorNum} · {floorLabel}</span>
          <h3 className="unit-name">{unit.unit_name || unit.unit_id}</h3>
        </div>
        <span className="unit-id-badge">{unit.unit_id}</span>
      </div>

      {/* ULPIN Hash Box — Blueprint Format */}
      <div className="ulpin-box">
        <div className="ulpin-header">
          <span className="ulpin-label">
            <Hash size={14} className="icon-blue" />
            3D ULPIN Code
          </span>
          <span className="cadastral-standard-badge">ISO 19152</span>
        </div>
        <div className="ulpin-code-row">
          <code className="ulpin-code-text" id="ulpin-display">{unit.ulpin}</code>
          <button
            className={`copy-ulpin-button ${copied ? 'copied' : ''}`}
            onClick={handleCopyULPIN}
            id="copy-ulpin-btn"
            title="Copy 3D ULPIN Code"
          >
            {copied ? <Check size={16} /> : <Copy size={16} />}
            <span>{copied ? 'Copied' : 'Copy'}</span>
          </button>
        </div>
        {/* ULPIN Format Breakdown */}
        <div className="ulpin-breakdown">
          {unit.ulpin.split('-').map((part, i) => (
            <span key={i} className="ulpin-part" title={['Parcel ID', 'Building Short', 'Floor Code', 'Unit Label', 'Geohash'][i] || 'Part'}>
              {part}
            </span>
          ))}
        </div>
      </div>

      {/* Specifications Grid */}
      <div className="specs-grid">
        <div className="spec-card">
          <div className="spec-icon-row">
            <Layers size={16} className="text-secondary" />
            <span className="spec-label">Floor</span>
          </div>
          <span className="spec-value">Level {floorNum}</span>
        </div>

        <div className="spec-card">
          <div className="spec-icon-row">
            <Ruler size={16} className="text-secondary" />
            <span className="spec-label">Floor Area</span>
          </div>
          <span className="spec-value">{areaSqm != null ? Number(areaSqm).toFixed(1) : '—'} m²</span>
        </div>

        <div className="spec-card">
          <div className="spec-icon-row">
            <Box size={16} className="text-secondary" />
            <span className="spec-label">Z Min</span>
          </div>
          <span className="spec-value">+{Number(zMin).toFixed(2)} m</span>
        </div>

        <div className="spec-card">
          <div className="spec-icon-row">
            <Box size={16} className="text-secondary" />
            <span className="spec-label">Z Max</span>
          </div>
          <span className="spec-value">+{Number(zMax).toFixed(2)} m</span>
        </div>

        <div className="spec-card">
          <div className="spec-icon-row">
            <AreaChart size={16} className="text-secondary" />
            <span className="spec-label">Floor Height</span>
          </div>
          <span className="spec-value">{Number(floorHeight).toFixed(2)} m</span>
        </div>

        <div className="spec-card">
          <div className="spec-icon-row">
            <Building2 size={16} className="text-secondary" />
            <span className="spec-label">Elevation</span>
          </div>
          <span className="spec-value">+{Number(zMin).toFixed(1)}–{Number(zMax).toFixed(1)}m</span>
        </div>
      </div>

      {/* Spatial Details */}
      <div className="details-list">
        <div className="detail-row">
          <span className="detail-key">
            <UserCheck size={14} /> Registered Owner
          </span>
          <span className="detail-val">{unit.owner || 'Private Title Holder'}</span>
        </div>

        <div className="detail-row">
          <span className="detail-key">
            <Compass size={14} /> Centroid (Lat, Lng)
          </span>
          <span className="detail-val font-mono">
            {centroid ? `${Number(centroid[0]).toFixed(5)}, ${Number(centroid[1]).toFixed(5)}` : '—'}
          </span>
        </div>

        <div className="detail-row">
          <span className="detail-key">
            <ShieldCheck size={14} /> Usage Type
          </span>
          <span className="detail-val highlight-green">{unit.use_type || 'Residential'}</span>
        </div>
      </div>

      {/* Action Footer */}
      <button className="btn-certificate btn-primary" onClick={downloadCertificate}>
        <Download size={16} />
        <span>Export 3D ULPIN Certificate</span>
      </button>
    </div>
  );
}
